version: '3.8'
services:
  e-store-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15022001
      POSTGRES_DB: eccommerce-db
    networks:
      - e-store

networks:
  e-store:
    driver: bridge